// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask01.Data;

#nullable disable

namespace TestTask01.Migrations
{
    [DbContext(typeof(TestTask01DB))]
    partial class TestTask01DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TestTask01.Models.Controgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Controgents");
                });

            modelBuilder.Entity("TestTask01.Models.OrderControgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ControgentId")
                        .HasColumnType("int");

                    b.Property<int?>("PolzovatelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ControgentId");

                    b.HasIndex("PolzovatelId");

                    b.ToTable("OrderControgents");
                });

            modelBuilder.Entity("TestTask01.Models.Polzovatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Polzovatels");
                });

            modelBuilder.Entity("TestTask01.Models.OrderControgent", b =>
                {
                    b.HasOne("TestTask01.Models.Controgent", "Controgent")
                        .WithMany("OrderControgents")
                        .HasForeignKey("ControgentId");

                    b.HasOne("TestTask01.Models.Polzovatel", "Polzovatel")
                        .WithMany("OrderControgents")
                        .HasForeignKey("PolzovatelId");

                    b.Navigation("Controgent");

                    b.Navigation("Polzovatel");
                });

            modelBuilder.Entity("TestTask01.Models.Controgent", b =>
                {
                    b.Navigation("OrderControgents");
                });

            modelBuilder.Entity("TestTask01.Models.Polzovatel", b =>
                {
                    b.Navigation("OrderControgents");
                });
#pragma warning restore 612, 618
        }
    }
}
